# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/perplexed',
                'doc_host': 'https://ncoop57.github.io',
                'git_url': 'https://github.com/ncoop57/perplexed',
                'lib_path': 'perplexed'},
  'syms': {'perplexed.core': {'perplexed.core.foo': ('core.html#foo', 'perplexed/core.py')}}}